# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"3\n\x0fReasoningSource\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\x10\n\x08node_ids\x18\x02 \x03(\t\"B\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\tthread_id\x18\x03 \x01(\t\"q\n\x0c\x43hatResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\'\n\x07sources\x18\x02 \x03(\x0b\x32\x16.agent.ReasoningSource\x12\x13\n\x0btokens_used\x18\x03 \x01(\x05\x12\x12\n\nlatency_ms\x18\x04 \x01(\x05\x32\x38\n\x05\x41gent\x12/\n\x04\x43hat\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponseB@Z>github.com/giakiet05/uit-ai-assistant/backend/internal/grpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/giakiet05/uit-ai-assistant/backend/internal/grpc/pb'
  _globals['_REASONINGSOURCE']._serialized_start=22
  _globals['_REASONINGSOURCE']._serialized_end=73
  _globals['_CHATREQUEST']._serialized_start=75
  _globals['_CHATREQUEST']._serialized_end=141
  _globals['_CHATRESPONSE']._serialized_start=143
  _globals['_CHATRESPONSE']._serialized_end=256
  _globals['_AGENT']._serialized_start=258
  _globals['_AGENT']._serialized_end=314
# @@protoc_insertion_point(module_scope)
